import './globals.css'
import { Inter } from 'next/font/google'
import { ToastContainer, toast } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css"
import Nav from './components/Navigation'
import BudgetBestieContextProvider from './lib/store/budget-bestie-context'
import AuthContextProvider from './lib/store/auth-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Budget Bestie',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <BudgetBestieContextProvider>
          <ToastContainer/>
            <Nav/>
            {children}
          </BudgetBestieContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
